[package]
name = "resume"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.8", features = ["macros"] }
base64 = "0.22.1"
bilrost = "0.1014.1"
# laser-pdf = {path = "../laser-pdf"}
laser-pdf = { git = "https://github.com/laser-pdf/laser-pdf.git", branch = "push-rpzsptvtqtrn" }
# laser-pdf = "0.5.0"
mimalloc = "0.1.48"
rand = "0.10.0"
tokio = { version = "1.50.0", features = ["full"] }
